language: python
sudo: false
cache: pip

matrix:
  include:
    - python: "3.5"
      env: TOXENV=test
    - python: "3.6"
      env: TOXENV=test
    - python: "3.5"
      env: TOXENV=static
    - python: "3.5"
      env: TOXENV=static

install: pip install tox

script: tox

after_success:
  - bash <(curl -s https://codecov.io/bash)
